# Generated by Django 6.0.7 on 2026-07-18 17:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('avatar', '0002_course_skill_category_skill_description_skill_course'),
        ('forum', '0001_initial'),
        ('tracker', '0002_project_projectsubmission_skillaward'),
    ]

    operations = [
        migrations.AddField(
            model_name='forumpost',
            name='course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='avatar.course'),
        ),
        migrations.AlterField(
            model_name='forumpost',
            name='subject',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='tracker.subject'),
        ),
    ]
