# Generated by Django 6.0.7 on 2026-07-17 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='mode',
            field=models.CharField(blank=True, choices=[('personal', 'Personal'), ('professional', 'Professional')], max_length=15, null=True),
        ),
    ]
