# Generated by Django 6.0.7 on 2026-07-18 16:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_profile_mode'),
        ('avatar', '0002_course_skill_category_skill_description_skill_course'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='avatar.course'),
        ),
    ]
