# Generated by Django 6.0.7 on 2026-07-26 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_profile_course'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='school',
            field=models.CharField(blank=True, choices=[('citu', 'Cebu Institute of Technology-University'), ('other', 'Other')], max_length=10),
        ),
        migrations.AddField(
            model_name='profile',
            name='school_id',
            field=models.CharField(blank=True, max_length=12),
        ),
        migrations.AddField(
            model_name='profile',
            name='under_evaluation',
            field=models.BooleanField(default=False),
        ),
    ]
