# Generated by Django 6.0.7 on 2026-07-28 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_profile_school_profile_school_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='middle_initial',
            field=models.CharField(blank=True, max_length=4),
        ),
    ]