# Generated by Django 6.0.7 on 2026-08-22 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_profile_middle_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='productivity_points',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
