from django.urls import path
from . import views

urlpatterns = [
    path('', views.subject_list, name='subject_list'),
    path('add/', views.add_subject, name='add_subject'),
    path('<int:subject_id>/', views.lesson_plan_view, name='lesson_plan_view'),
    path('<int:subject_id>/add-topic/', views.add_topic, name='add_topic'),
    path('topic/<int:topic_id>/add-activity/',
         views.add_activity, name='add_activity'),
    path('activity/<int:activity_id>/',
         views.activity_detail, name='activity_detail'),
    path('<int:subject_id>/add-project/',
         views.add_project, name='add_project'),
    path('project/<int:project_id>/', views.project_detail, name='project_detail'),
    path('submission/<int:submission_id>/evaluate/',
         views.evaluate_submission, name='evaluate_submission'),
    path('submission/<int:submission_id>/finish/',
         views.finish_evaluation, name='finish_evaluation'),
    path('<int:subject_id>/manage-students/',
         views.manage_students, name='manage_students'),
    path('activity/<int:activity_id>/add-skill/',
         views.add_activity_skill, name='add_activity_skill'),
    path('<int:subject_id>/manage-students/add/<int:student_id>/',
         views.add_student_to_subject, name='add_student_to_subject'),
    path('<int:subject_id>/manage-students/remove/<int:student_id>/',
         views.remove_student_from_subject, name='remove_student_from_subject'),
    path('tasks/', views.task_list, name='task_list'),
    path('tasks/add-activity/', views.add_task_activity, name='add_task_activity'),
    path('tasks/add-project/', views.add_task_project, name='add_task_project'),
    path('personal-tasks/', views.personal_task_list, name='personal_task_list'),
    path('personal-tasks/add/', views.add_personal_task, name='add_personal_task'),
    path('personal-tasks/<int:task_id>/complete/',
         views.complete_personal_task, name='complete_personal_task'),
    path('personal-tasks/<int:task_id>/',
         views.personal_task_detail, name='personal_task_detail'),
    path('<int:subject_id>/calendar/', views.calendar_view, name='calendar_view'),
    path('subject/<int:subject_id>/delete/',
         views.delete_subject, name='delete_subject'),
    path('topic/<int:topic_id>/delete/',
         views.delete_topic, name='delete_topic'),
    path('activity/<int:activity_id>/delete/',
         views.delete_activity, name='delete_activity'),
    path('project/<int:project_id>/delete/',
         views.delete_project, name='delete_project'),
    path('personal-tasks/<int:task_id>/delete/',
         views.delete_personal_task, name='delete_personal_task'),
]
