from django.urls import path
from . import views

urlpatterns = [
    path('', views.subject_list, name='subject_list'),
    path('add/', views.add_subject, name='add_subject'),
    path('<int:subject_id>/customize/', views.customize_subject, name='customize_subject'),
    path('<int:subject_id>/', views.lesson_plan_view, name='lesson_plan_view'),
    path('<int:subject_id>/add-topic/', views.add_topic, name='add_topic'),
    path('topic/<int:topic_id>/edit/', views.edit_topic, name='edit_topic'),
    path('topic/<int:topic_id>/toggle-semester-split/', views.toggle_semester_split, name='toggle_semester_split'),
    path('topic/<int:topic_id>/', views.topic_detail, name='topic_detail'),
     path('topic/<int:topic_id>/activities/', views.topic_activities_view, name='topic_activities'),
     path('topic/<int:topic_id>/assignments/', views.topic_assignments_view, name='topic_assignments'),
     path('topic/<int:topic_id>/quizzes/', views.topic_quizzes_view, name='topic_quizzes'),
     path('topic/<int:topic_id>/documents/', views.topic_documents_view, name='topic_documents'),
     path('document/<int:document_id>/', views.document_view, name='document_view'),
     path('topic/<int:topic_id>/images/', views.topic_images_view, name='topic_images'),
     path('topic/<int:topic_id>/add-activity/',
         views.add_activity, name='add_activity'),
    path('activity/<int:activity_id>/',
         views.activity_detail, name='activity_detail'),
    path('topic/<int:topic_id>/add-assignment/',
         views.add_assignment, name='add_assignment'),
    path('assignment/<int:assignment_id>/',
         views.assignment_detail, name='assignment_detail'),
    path('<int:subject_id>/add-project/',
         views.add_project, name='add_project'),
    path('project/<int:project_id>/', views.project_detail, name='project_detail'),
    path('submission/<int:submission_id>/evaluate/',
         views.evaluate_submission, name='evaluate_submission'),
    path('submission/<int:submission_id>/finish/',
         views.finish_evaluation, name='finish_evaluation'),
    path('<int:subject_id>/manage-students/',
         views.manage_students, name='manage_students'),
     path('<int:subject_id>/manage-students/skills-summary/',
         views.class_skill_summary, name='class_skill_summary'),
    path('<int:subject_id>/gradesheet/',
         views.gradesheet_view, name='gradesheet_view'),
     path('<int:subject_id>/gradesheet/grade-queue/',
          views.grade_subject_queue, name='grade_subject_queue'),
     path('activity-completion/<int:completion_id>/grade/',
         views.grade_activity_completion, name='grade_activity_completion'),
     path('activity/<int:activity_id>/grade-queue/', views.grade_activity_queue, name='grade_activity_queue'),
     path('assignment-completion/<int:completion_id>/grade/',
          views.grade_assignment_completion, name='grade_assignment_completion'),
     path('assignment/<int:assignment_id>/grade-queue/', views.grade_assignment_queue, name='grade_assignment_queue'),
    path('<int:subject_id>/manage-students/add/<int:student_id>/',
         views.add_student_to_subject, name='add_student_to_subject'),
    path('<int:subject_id>/manage-students/remove/<int:student_id>/',
         views.remove_student_from_subject, name='remove_student_from_subject'),
    path('tasks/', views.task_list, name='task_list'),
    path('calendar/', views.week_calendar_view, name='week_calendar_view'),
    path('tasks/add-activity/', views.add_task_activity, name='add_task_activity'),
    path('tasks/add-project/', views.add_task_project, name='add_task_project'),
    path('personal-tasks/', views.personal_task_list, name='personal_task_list'),
    path('personal-tasks/add/', views.add_personal_task, name='add_personal_task'),
    path('personal-tasks/<int:task_id>/complete/',
         views.complete_personal_task, name='complete_personal_task'),
    path('personal-tasks/<int:task_id>/',
         views.personal_task_detail, name='personal_task_detail'),
    path('<int:subject_id>/calendar/', views.calendar_view, name='calendar_view'),
    path('subject/<int:subject_id>/delete/',
         views.delete_subject, name='delete_subject'),
    path('topic/<int:topic_id>/delete/',
         views.delete_topic, name='delete_topic'),
     path('activity/<int:activity_id>/delete/',
         views.delete_activity, name='delete_activity'),
    path('assignment/<int:assignment_id>/delete/',
         views.delete_assignment, name='delete_assignment'),
    path('project/<int:project_id>/delete/',
         views.delete_project, name='delete_project'),
    path('personal-tasks/<int:task_id>/delete/',
         views.delete_personal_task, name='delete_personal_task'),                   
     path('<int:subject_id>/gradesheet/',
          views.gradesheet_view, name='gradesheet_view'),
     path('<int:subject_id>/gradesheet/weights/',
          views.update_grade_weights, name='update_grade_weights'),
     path('<int:subject_id>/my-gradesheet/',
          views.my_gradesheet_view, name='my_gradesheet_view'),
     path('<int:subject_id>/analytics/', views.subject_analytics, name='subject_analytics'),
     path('<int:subject_id>/my-analytics/', views.my_subject_analytics, name='my_subject_analytics'),
     path('topic/<int:topic_id>/add-quiz/', views.add_quiz, name='add_quiz'),
     path('quiz/<int:quiz_id>/add-skill/', views.add_quiz_skill_weight, name='add_quiz_skill'),
     path('quiz/<int:quiz_id>/', views.quiz_detail, name='quiz_detail'),
     path('quiz-completion/<int:completion_id>/grade/', views.grade_quiz_completion, name='grade_quiz_completion'),
     path('quiz/<int:quiz_id>/delete/', views.delete_quiz, name='delete_quiz'),
     path('<int:subject_id>/exam/<str:exam_type>/', views.exam_router, name='exam_router'),
     path('<int:subject_id>/exam/<str:exam_type>/add/', views.add_exam, name='add_exam'),
     path('exam/<int:exam_id>/add-skill/', views.add_exam_skill_weight, name='add_exam_skill'),
     path('exam/<int:exam_id>/', views.exam_detail, name='exam_detail'),
     path('exam-completion/<int:completion_id>/grade/', views.grade_exam_completion, name='grade_exam_completion'),
     path('exam-completion/<int:completion_id>/grade/', views.grade_exam_completion, name='grade_exam_completion'),
     path('exam/<int:exam_id>/delete/', views.delete_exam, name='delete_exam'),
]