# Generated by Django 6.0.7 on 2026-07-18 18:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('avatar', '0002_course_skill_category_skill_description_skill_course'),
        ('tracker', '0002_project_projectsubmission_skillaward'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activity',
            name='skills',
        ),
        migrations.CreateModel(
            name='ActivitySkillPoints',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('points', models.PositiveIntegerField(default=10)),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skill_points', to='tracker.activity')),
                ('skill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='avatar.skill')),
            ],
            options={
                'unique_together': {('activity', 'skill')},
            },
        ),
    ]
