# Generated by Django 6.0.7 on 2026-07-19 19:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0003_remove_activity_skills_activityskillpoints'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activity',
            name='completed_by',
        ),
        migrations.RemoveField(
            model_name='projectsubmission',
            name='content',
        ),
        migrations.AddField(
            model_name='projectsubmission',
            name='document',
            field=models.FileField(blank=True, null=True, upload_to='project_submissions/documents/'),
        ),
        migrations.AddField(
            model_name='projectsubmission',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='project_submissions/images/'),
        ),
        migrations.CreateModel(
            name='ActivityCompletion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='activity_submissions/images/')),
                ('document', models.FileField(blank=True, null=True, upload_to='activity_submissions/documents/')),
                ('completed_at', models.DateTimeField(auto_now_add=True)),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='completions', to='tracker.activity')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activity_completions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('activity', 'student')},
            },
        ),
    ]
