# Generated by Django 6.0.7 on 2026-07-19 21:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('avatar', '0002_course_skill_category_skill_description_skill_course'),
        ('tracker', '0005_personaltask'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='personaltask',
            name='skills',
        ),
        migrations.AddField(
            model_name='personaltask',
            name='skill_main',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='personal_tasks_main', to='avatar.skill'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='personaltask',
            name='skill_secondary',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='personal_tasks_secondary', to='avatar.skill'),
        ),
        migrations.AddField(
            model_name='personaltask',
            name='skill_tertiary',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='personal_tasks_tertiary', to='avatar.skill'),
        ),
        migrations.AddField(
            model_name='personaltask',
            name='weekly_days',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='personaltask',
            name='deadline',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='personaltask',
            name='repeat',
            field=models.CharField(choices=[('none', 'Does not repeat'), ('daily', 'Daily'), ('weekly', 'Weekly'), ('forever', 'Repeat forever')], default='none', max_length=10),
        ),
    ]
