# Generated by Django 6.0.7 on 2026-07-19 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0006_remove_personaltask_skills_personaltask_skill_main_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='personaltask',
            name='no_deadline',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='personaltask',
            name='repeat',
            field=models.CharField(choices=[('none', 'Does not repeat'), ('daily', 'Daily'), ('weekly', 'Weekly')], default='none', max_length=10),
        ),
    ]
