# Generated by Django 6.0.7 on 2026-07-20 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0007_personaltask_no_deadline_alter_personaltask_repeat'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='instructions',
            field=models.TextField(blank=True),
        ),
    ]
