# Generated by Django 6.0.7 on 2026-07-21 10:33

import datetime
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0008_activity_instructions'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='topic',
            name='week_number',
        ),
        migrations.AddField(
            model_name='activity',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2026, 7, 21, 10, 32, 15, 816202, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='project',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='topic',
            name='end_date',
            field=models.DateField(default=datetime.datetime(2026, 7, 21, 10, 33, 11, 608897, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='topic',
            name='start_date',
            field=models.DateField(default=datetime.datetime(2026, 7, 21, 10, 33, 15, 931829, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
    ]
