# Generated by Django 6.0.7 on 2026-07-25 19:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('avatar', '0002_course_skill_category_skill_description_skill_course'),
        ('tracker', '0009_remove_topic_week_number_activity_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='max_score',
            field=models.PositiveIntegerField(default=100),
        ),
        migrations.AddField(
            model_name='activity',
            name='skill_main',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activities_main', to='avatar.skill'),
        ),
        migrations.AddField(
            model_name='activity',
            name='skill_secondary',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activities_secondary', to='avatar.skill'),
        ),
        migrations.AddField(
            model_name='activity',
            name='skill_tertiary',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activities_tertiary', to='avatar.skill'),
        ),
        migrations.AddField(
            model_name='activitycompletion',
            name='graded',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='activitycompletion',
            name='score',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='ActivitySkillPoints',
        ),
    ]
