# Generated by Django 6.0.7 on 2026-07-26 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0010_activity_max_score_activity_skill_main_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='max_score',
            field=models.PositiveIntegerField(default=100),
        ),
        migrations.AddField(
            model_name='projectsubmission',
            name='score',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
