# Generated by Django 6.0.7 on 2026-07-27 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0012_subject_activity_weight_subject_project_weight'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='at_risk_threshold',
            field=models.PositiveIntegerField(default=75),
        ),
    ]
