# Generated by Django 6.0.7 on 2026-08-04 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0013_subject_at_risk_threshold'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='document',
            field=models.FileField(blank=True, null=True, upload_to='topic_materials/documents/'),
        ),
        migrations.AddField(
            model_name='topic',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='topic_materials/images/'),
        ),
    ]
