# Generated by Django 6.0.7 on 2026-08-06 01:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0016_quiz_quizcompletion_quizskillweight'),
    ]

    operations = [
        migrations.RenameField(
            model_name='quiz',
            old_name='passing_score',
            new_name='passing_percentage',
        ),
    ]
