# Generated by Django 6.0.7 on 2026-08-06 06:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('avatar', '0002_course_skill_category_skill_description_skill_course'),
        ('tracker', '0017_rename_passing_score_quiz_passing_percentage'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuizSkillAward',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('delta', models.IntegerField()),
                ('points_before', models.PositiveIntegerField()),
                ('points_after', models.PositiveIntegerField()),
                ('completion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skill_awards', to='tracker.quizcompletion')),
                ('skill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='avatar.skill')),
            ],
        ),
    ]
