# Generated by Django 6.0.7 on 2026-08-07 04:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('avatar', '0002_course_skill_category_skill_description_skill_course'),
        ('tracker', '0018_quizskillaward'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Exam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exam_type', models.CharField(choices=[('prelim', 'Prelim Exam'), ('midterm', 'Midterm Exam'), ('prefinal', 'Prefinal Exam'), ('final', 'Final Exam')], max_length=10)),
                ('instructions', models.TextField(blank=True)),
                ('deadline', models.DateField()),
                ('max_score', models.PositiveIntegerField(default=100)),
                ('passing_percentage', models.PositiveIntegerField(default=60)),
                ('file', models.FileField(blank=True, null=True, upload_to='exam_materials/files/')),
                ('image', models.ImageField(blank=True, null=True, upload_to='exam_materials/images/')),
                ('link', models.URLField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exams', to='tracker.subject')),
            ],
            options={
                'unique_together': {('subject', 'exam_type')},
            },
        ),
        migrations.CreateModel(
            name='ExamCompletion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marked_done_at', models.DateTimeField(auto_now_add=True)),
                ('score', models.PositiveIntegerField(blank=True, null=True)),
                ('graded', models.BooleanField(default=False)),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='completions', to='tracker.exam')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exam_completions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('exam', 'student')},
            },
        ),
        migrations.CreateModel(
            name='ExamSkillAward',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('delta', models.IntegerField()),
                ('points_before', models.PositiveIntegerField()),
                ('points_after', models.PositiveIntegerField()),
                ('completion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skill_awards', to='tracker.examcompletion')),
                ('skill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='avatar.skill')),
            ],
        ),
        migrations.CreateModel(
            name='ExamSkillWeight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('percentage', models.PositiveIntegerField()),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skill_weights', to='tracker.exam')),
                ('skill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='avatar.skill')),
            ],
            options={
                'unique_together': {('exam', 'skill')},
            },
        ),
    ]
