# Generated by Django 6.0.7 on 2026-08-18 13:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('avatar', '0002_course_skill_category_skill_description_skill_course'),
        ('tracker', '0025_personaltask_start_end_time'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='assignment_weight',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='subject',
            name='final_assignment_weight',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='subject',
            name='midterm_assignment_weight',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('instructions', models.TextField(blank=True)),
                ('deadline', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('max_score', models.PositiveIntegerField(default=100)),
                ('term', models.CharField(blank=True, choices=[('midterm', 'Midterm'), ('final', 'Final')], default='midterm', max_length=7)),
                ('skill_main', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assignments_main', to='avatar.skill')),
                ('skill_secondary', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assignments_secondary', to='avatar.skill')),
                ('skill_tertiary', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assignments_tertiary', to='avatar.skill')),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='tracker.topic')),
            ],
        ),
        migrations.CreateModel(
            name='AssignmentCompletion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='assignment_submissions/images/')),
                ('document', models.FileField(blank=True, null=True, upload_to='assignment_submissions/documents/')),
                ('completed_at', models.DateTimeField(auto_now_add=True)),
                ('score', models.PositiveIntegerField(blank=True, null=True)),
                ('graded', models.BooleanField(default=False)),
                ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='completions', to='tracker.assignment')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignment_completions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('assignment', 'student')},
            },
        ),
    ]
