# Generated by Django 6.0.7 on 2026-08-20 00:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0026_subject_assignment_weight_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='term',
            field=models.CharField(blank=True, choices=[('midterm', 'Midterm'), ('final', 'Final')], default='midterm', max_length=7),
        ),
        migrations.AddField(
            model_name='subject',
            name='final_project_weight',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='subject',
            name='midterm_project_weight',
            field=models.PositiveIntegerField(default=0),
        ),
    ]