# Generated by Django 6.0.7 on 2026-08-20 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0027_project_term_subject_final_project_weight_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exam',
            name='max_score',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='exam',
            name='passing_percentage',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='max_score',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='passing_percentage',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
