# Generated by Django 6.0.7 on 2026-08-22 15:32

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0028_alter_exam_max_score_alter_exam_passing_percentage_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='productivity_penalized_students',
            field=models.ManyToManyField(blank=True, related_name='activity_productivity_penalties', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='activitycompletion',
            name='productivity_processed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='assignment',
            name='productivity_penalized_students',
            field=models.ManyToManyField(blank=True, related_name='assignment_productivity_penalties', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='assignmentcompletion',
            name='productivity_processed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='personaltask',
            name='productivity_processed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='project',
            name='productivity_penalized_students',
            field=models.ManyToManyField(blank=True, related_name='project_productivity_penalties', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='projectsubmission',
            name='productivity_processed',
            field=models.BooleanField(default=False),
        ),
    ]
